server.port=8081
spring.datasource.url=jdbc:postgresql://ca-postgres:5432/ca_db
spring.datasource.username=ca
spring.datasource.password=root
spring.datasource.driverClassName=org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
ca.keystore.password=${KEYSTORE_PASSWORD}